NCEAS/metacatui

src/js/views/MetadataIndexView.js

Closes #453
Fixed issue where FGDC SID not viewing
The solution to this was to add `seriesId` to the
query in `MetadataIndexView.render()`.

FGDC format cannot be viewed by SID

---

src/js/models/metadata/eml211/EML211.js

In ESS-DIVE's effort to use `<additionalInfo/>` a couple of issues were discovered which prevented us from generating the following EML in `<dataset/>`. This pull request addresses those two issues
```
<additionalInfo>
<section>
<title>Reference Papers</title>
<para>Citation or DOI</para>
<para>Citation or DOI</para>
</section>
</additionalInfo>
```

additionalinfo support

---

src/css/metacatui-common.css

Prior to this fix, an entity with many (~50+) attributes wouldn't display in a user-friendly manner. See #511 for a demo. I chose a max-height of 700px because that's about what size the attribute detail pane (on the right) gets automatically set to by the my browser for a simple attribute.
Partially addresses #511
I've tested this out with the arctic and dataone themes.

Scroll the variables (attributes) list when needed

---

src/js/models/SolrResult.js

This is the fix we are using in ESS-DIVE to determine if a data package already has a DOI.  Thought I would submit the pull request since we already had the solution.
Closes #479

SolrResult.isDOI does not consider the seriesID

---

src/js/app.js

Closes #575 
This morning `https://code.jquery.com/jquery-1.9.1.min` is unavailable for a time which made ESS-DIVE available. 
Since [`jquery.1.9.1.min.js`](https://github.com/NCEAS/metacatui/blob/master/src/components/jquery-1.9.1.min.js) is already checked into the metacatui code base I propose referencing it in `app.js` [here](https://github.com/NCEAS/metacatui/blob/403baccb4af080aecc33512c2c2a3962b080582c/src/js/app.js#L37).

Locally reference jquery.1.9.1.min.js

---

src/js/views/CitationView.js

This modifies the look of the CitationView when the `datasoruce`
is `urn:node:PANGAEA` and the metadata Object has a SID. When that
is the case, only the SID will be displayed.
@laurenwalker does this conflict with your work on making URIs in the CitationView clickable? 
I did a minor amount of testing and this appears to work as intended.

Add PANGAEA-specific override to CitationView

---

src/js/views/MetadataView.js

This behavior is slightly different than the Copy Citation in that it just replaces the innerHTML with a ✔ and, after 500ms, returns the old button (or other element) innerHTML. This'll also work if someone needs copiables in other areas of the view service later on.
Preview:
Closes #591

Add copy-on-click support to the DOM returned by the view service

---

src/js/views/MetadataView.js

I had some bad logic in my initial implementation that caused the button text to permanently become a ✔️ if the user clicks the button fast. This was because the callback that re-sets the text back to its original value picks up the termporary value. Now the button will always return to "Copy".

Fix bug in MetadataView.insertCopiables

---

src/js/models/metadata/eml211/EML211.js

ESS-DIVE extends MetacatUI to make use of `<additionalInfo>` entity.  There was a previous pull request that enabled the use of `<additionalInfo>` in `emlText`.  See Issue #493.   On `EML211.parse()` it was discovered that `additionalinfo` was not using `nodeNameMap()` to convert to the camel-case entity name (`additionalInfo`)
The changes are as follows:
- additionalInfo was not being converted to camel-case (`additionalinfo > additionalInfo`)
- moved local variable convertedName up to beginning of loop for reuse.

Needed to use convertedName for emlText

---

src/js/routers/router.js
src/js/templates/metaTagsHighwirePress.html
src/js/themes/arctic/routers/router.js
src/js/themes/dataone/routers/router.js
src/js/themes/goa/routers/router.js
src/js/themes/nceas/routers/router.js
src/js/views/MetadataView.js

This change required a refactor of the JSONLD work to DRY up code that needed similar logic between the JSONLD and Highwire Press code.
While I was in here, I realized we weren't properly removing stale JSONLD so I added a method that is attached to all routers' 'route' event that clears the stale JSONLD and also the Highwire Press meta tags.
Resolves #491 if we think this is enough for now.

Add support for Highwire Press bibliographic meta tags

---

src/js/views/DownloadButtonView.js

Solved by changing the CSS of that button cursor to default and checking if the button element has the `disabled` attribute.
- The download button works, as expected, for rest of the cases.

Disable download if the package is too large.

---

src/css/metacatui-common.css
src/js/views/CitationListView.js
src/js/views/MetricsChartView.js

This PR includes the changes mentioned in the MDC call today, specifically this update:
- changes the "No data to display yet" text to "This dataset hasn’t been [cited/downloaded/viewed] yet."
- changes the date range of the slider/context chart to match the date range of the data. In addition, the zoom to: "year" button will now only appear if there is at least 1 year of data to show (the "month" and "data" buttons remain in any case).
- increases the opacity of the fill area in an attempt to make the chart appear more consistent with the overall colour scheme. The most recent commit can be `reset` if this isn't the desired look.

Metrics chart tweaks

---

src/css/metacatui-common.css
src/index.html
src/js/themes/arctic/css/metacatui.css
src/js/themes/dataone/css/metacatui.css
src/js/themes/dataone/models/AppModel.js
src/js/themes/default/css/metacatui.css
src/js/themes/goa/css/metacatui.css
src/js/themes/knb/css/metacatui.css
src/js/themes/nceas/css/metacatui.css
src/js/views/MetricsChartView.js

The chart also has a couple of new features:
- The total views/downloads is displayed in the upper left hand corner. This total updates to match the date range in focus as the user scrolls or zooms.
- When the user mouses over either a bar or an x-axis label, a tooltip window appears that displays the number of views/downloads for the given month.
- The chart now includes some subtle animations (when the chart first loads and when the user switches date ranges).
This PR resolves issue #778 and issue #785.

Switched metrics line chart to a bar chart

---

src/css/metacatui-common.css
src/js/models/AppModel.js
src/js/templates/metadataControls.html
src/js/themes/arctic/models/AppModel.js
src/js/themes/dataone/models/AppModel.js
src/js/themes/knb/models/AppModel.js
src/js/themes/nceas/models/AppModel.js
src/js/views/MetadataView.js

This PR is for a feature that allows a user to come from DataONE to Whole Tale with the intent on using a data package. To do this I added a dropdown menu next to the copy button in the metadata view.
I added a flag to the appmodels so we can easily toggle the feature on and off. You can see where the application uses this in `src/js/views/MetadataView.js`
I added the dropdown menu to `src/js/templates/metadataControls.html`. It uses the result from above to check if it should render the content.
I construct the links for each compute environment in `src/js/views/MetadataView.js`

Feature: Analyze Button

---

src/js/models/DataONEObject.js

Update includes:
- Pointing to /meta endpoint for the added `updateSysMeta()` function.
- systemMetadataOnly option is passed to serializeSysMeta function to be able to ignore the null setting of checksum.
Closes #1148

Adds updating sysmetadata function to DataONEObject file.

---

src/js/models/metadata/eml211/EML211.js
src/js/templates/metadata/EMLParty.html
src/js/views/metadata/EML211View.js

Closes https://github.com/NCEAS/metacatui/issues/521
As decided in #521, the initial implementation adds simple up/down buttons alongside each party view. Clicking either button moves the party up or down on the page and also updates the underlying EML model so the serialized document reflects the change. When re-ordering creators, the citation preview automatically updates to reflect the changes.
Three things I'd appreciate an extra look at are:
1. I don't let you move a party down below the new/placeholder party so the placeholder is always the last item in the group. It made sense to me to leave the placeholder at the bottom.
2. I didn't wanna to get too fancy with the up/down buttons so I just put them to the left of the party menu. Very much open to feedback here.
3. I wanted to …

Add the ability to re-order parties

---

src/css/metacatui-common.css

This is a small css change that was breaking the alignment for checkboxes filters.

Fixes checkboxes filters alignment

---

src/js/models/DataONEObject.js

Bug fix where the editor sets the `formatId` to `application/vnd.ms-excel` for csv files with their mime type set as excel (only occurs for excel-exported csvs in windows).  
I decided to add a new method because `DataONEObject.getFormatId` [returns](https://github.com/NCEAS/metacatui/blob/9d4490b7a908f818db6301e4560fe6d8203e58ac/src/js/models/DataONEObject.js#L784) the first `formatId` that matches an object's mediatype.  The body of `sanitizeFormatId` would need to be inserted before that first return, so an additional method seemed cleaner.  
Some possible changes: 
1. This could be condensed into one line - I thought this was more readable. 
```
var formatId = this.sanitizeFormatId(this.get("formatId") || this.getFormatId());
xml.find("formatid").text(formatId);
```
2. I grabbed this …

Fix bug where formatId is set to application/vnd.ms-excel for csvs 

---

src/js/views/metadata/EML211EditorView.js

In order to not remove the temporary message when removing all validation alerts, a selective css selector is used to exclude alerts with temporary message.
closes #1534

Selectively remove alerts on validation

---

src/css/metacatui-common.css
src/js/templates/bioportalAnnotationTemplate.html
src/js/views/AnnotationView.js

Before this change, clicking anywhere in the annotation pill shows a single popover providing more information about the `valueURI`. No extra information can be found about the `propertyURI` beyond its label.
Now, you get two separate popovers, and each one can show more information about each term (if found):
This change is tied with https://github.com/NCEAS/metacat/pull/1518 which modifies the underlying DOM structure returned by the view service. For perfect functionality, this change requires a Metacat upgrade. However, the changes were made to be relatively backwards compatible:
| | Old Metacat | New Metacat |
|-:|:-:|:-:|
|**Old MetacatUI** | ✅ | Pill has one minor glitch, old popover works |
|**New MetacatUI** | Pill looks good, no popovers | ✅ |
The minor glitch above when an old …

Refactor AnnotationView to show two separate popovers instead of a single one

---

src/js/models/AppModel.js
src/js/models/Search.js
src/js/templates/search.html
src/js/themes/arctic/config.js
src/js/views/DataCatalogView.js

This PR adds a `private` dataset filter to the main search window. The changes are:
- adding a new filter category `Access`
- a single option filter option `Private datasets`
- if this item is checked, the following clause is added to dataset retrieval Solr query: `-isPublic:true`

Feature filter private #1902

---

src/css/map-view.css
src/js/templates/maps/layer-detail.html
src/js/templates/maps/layer-navigation.html
src/js/views/maps/LayerDetailView.js
src/js/views/maps/LayerDetailsView.js

- Add section options to LayerDetailsView that allows sections to not display a title or not be collapsible
- Add a map button "emphasis" style. The button will use the `portal-secondary-color` if one is set, or a default color otherwise.
- Use the "emphasis" button style on the Zoom To button, move the navigation section to the top of the LayerDetailsView, and hide the title & collapse button
Fixes issue #1974

Make zoom button in Cesium more obvious

---

src/css/map-view.css
src/js/models/maps/assets/MapAsset.js
src/js/views/maps/LayerDetailsView.js
src/js/views/maps/LayerItemView.js

This PR adds support for configuring notifications in Cesium maps that are specific to individual layers. A notification is configured by adding a `notification` property to a layer, for example:
``` json
{
"layers": [
{
"label": "Ice Wedge Polygons",
"type": "Cesium3DTileset",
"notification": {
"badge": "Preview",
"style": "green",
"message": "Pan-arctic coverage will be available for this layer soon! While the data pipeline is under development, a subset of the data is available here."
}
}
]}
```
This adds a badge element next to the layer name in the layers list, and a longer message in the layer details panel:
Five styles of notifications are available:
The image above comes from the the test portal `permafrost-test-portal` on `urn:node:mnTestARCTIC` - this portal could be used to …

Enable layer-level notifications in Cesium map

---

src/js/models/metadata/eml211/EMLProject.js

Enhances EMLProject.updaeDOM to allow xmlID to be set into the
project elements id attribute.
Closes #1999

EMLProject add ability to set id attribute

---

src/js/models/metadata/eml211/EML211.js

Combination of EML annotation and custom xml safe generated identifiers
raise error on save
+ replaces the use of this.getXMLSafeID() with
this.getUniqueEntityId(this) in `EML211.serialize()` to make sure that the identifier is
unique.
Closes #2038

Fixes duplicate ids with EML annotations

---

src/js/collections/ProjectList.js
src/js/models/AppModel.js
src/js/models/Project.js
src/js/routers/router.js
src/js/templates/projectInfo.html
src/js/views/ProjectView.js
test/config/tests.json
test/js/specs/unit/collections/ProjectList.spec.js
test/js/specs/unit/models/project/Project.spec.js

Closes #1945
* Adds a base Project model and collection that can be populated
either from a default or a direct API. In the case of populating
from the API, extending member nodes will have to extend the Parse
function if any data structure handling is needed.
* Adds tests for project model and collection.
* Adds a Project view with some functinality to handle basic view
project selection and rendering.
* Adds a projects info template as a placeholder for extending nodes.
Co-authors: Mario Melara, Val Hendrix

Adds Project Base Model, View and Placeholder HTML

---

src/js/models/AppModel.js
src/js/models/Search.js
src/js/templates/search.html

Enables turning on project search in the DataCatalogView.
+ Documentation change made to AppModel.js (provide projectText in
example for defaultSearchFilters
+ Updates Backbone Search model to include projectText
+ Updates search.html template to optionally render the project search
filter
Closes #2044

Add project search filter option

---

src/js/models/Stats.js

Part of #2041 
MetacatUI was sending URL encoded query strings as part of POST request query parameter which was causing issues with SOLR request resulting in `500` error. The commit in this PR fixes those errors for Portal Metrics.

Resolves issues with infinite spinners for portal metrics

---

README.md
docs/index.md

Feature for adding a DOI citation for MetacatUI. The DOI already exists (I created it).

Add DOI reference and software citation for MetacatUI.

---

src/css/metacatui-common.css
src/js/models/AppModel.js
src/js/models/metadata/eml211/EMLTaxonCoverage.js
src/js/views/metadata/EML211View.js
src/js/views/metadata/EMLTaxonView.js
src/js/views/searchSelect/SearchableSelectView.js

This PR introduces the configurable and optional "Quick Add Taxa" feature in the EML editor. This feature allows repositories to set a list or lists of common taxa to make entry in the EML a little quicker. Here's a screen shot of how it looks for the SCTLD test site:
Here is an example of the EML that it generates. Note that this PR also adds support for the taxonId and commonName elements, which were previously being lost if an EML document was edited in our Editor.
```
<taxonomicCoverage>
<taxonomicClassification>
<taxonRankName>species</taxonRankName>
<taxonRankValue>Agaricia agaricites</taxonRankValue>
<taxonId provider="https://www.itis.gov">53050</taxonId>
</taxonomicClassification>
<taxonomicClassification>
<taxonRankName>species</taxonRankName>
<taxonRankValue>Acropora …
```

Quick Add Taxa feature in the EML editor 🪸

---

src/js/views/MetadataIndexView.js
src/js/views/MetadataView.js

Added some better error handling in the MetadataIndexView.js and the MetadataView.js to handle cases where the response is something unexpected. Now the UI will show an error rather than an infinite spinner.
Fixes #2144

Improve error handling of view service response

---

src/js/themes/dataone/css/metacatui.css
src/js/views/MarkdownView.js
src/js/views/TOCView.js
src/js/views/portals/PortalSectionView.js

- Add min height to markdown sections with portals
- Also rename methods from postRender to what they do, because backbone calls these methods automatically even though this isn't documented!
fixes #2195

Prevent weird TOC placement in portals

---

src/js/views/maps/FeatureInfoView.js

Adjust height of feature info panel in Cesium map

---

src/js/models/metadata/eml211/EMLGeoCoverage.js
src/js/templates/metadata/EMLGeoCoverage.html
src/js/views/metadata/EMLGeoCoverageView.js
test/config/tests.json
test/js/specs/unit/models/metadata/eml211/EMLGeoCoverage.spec.js

Add validation rules to the EmlGeoCoverage model to prevent:
- North and South coordinates from being reversed (N must be > S)
- Bounding boxes containing either the North or South pole
- Bounding boxes crossing the anti-meridian
Show error messages in the editor when values described above are entered. Add tests for the EmlGeoCoverage model.
Also fix the HTML input regex pattern for coordinate fields.

Prevent impossible & problematic coordinates from being entered in the editor

---

src/css/map-view.css
src/css/metacatui-common.css
src/js/themes/knb/css/metacatui.css

- Set a fixed height for body element to force map view to appear on page.
- Add some padding to allow for scrollbar in layers toolbar.
- Fix issue with cutting off last layer in toolbar on narrow laptop screen due to a hardcoded value for the header height.
GitHub issue: https://github.com/NCEAS/metacatui/issues/2242

Add CSS to support scrolling in layers toolbar in the Cesium map view

---

src/css/map-view.css

With no interactable elements the transparent toolbar blocked the Cesium view. This change enables pointer events only on the parts of the toolbar with content.
GitHub issue: #2207

Disable pointer events on transparent toolbar blocking Cesium map

---

src/css/metacatui-common.css
src/js/themes/arctic/css/metacatui.css
src/js/themes/default/css/metacatui.css
src/js/themes/knb/css/metacatui.responsive.css

Fixes #2261.
The issue was occurring in all themes that use Cesium. Moving the fix to `metacatui.common.css` fixes the issue for all themes.

Bugfix 2261 scale bar covers nav

---

src/css/metacatui-common.css
src/js/views/portals/PortalSectionView.js
src/js/views/portals/PortalView.js
src/js/views/portals/PortalVisualizationsView.js

From [my comment](https://github.com/NCEAS/metacatui/issues/2265#issuecomment-1949332448) on the issue:
> My solution to this is a little different than the [above method](https://github.com/NCEAS/metacatui/issues/2265#issuecomment-1936748651), instead of using the `.PortalView` element, I set `height: 100%` on `document.style.body` in `PortalVisualizationsView`, and remove the property in `PortalSectionView`. I did this because it echoes the way [the `--footer-height` is set and unset](https://github.com/NCEAS/metacatui/blob/758ff8e3710637d9fdf406a9c2383e56ff5be877/src/js/views/FooterView.js#L30-L42). If it would be cleaner for me to do this another way (such as setting this on `.PortalView`), I'm happy to switch to a different method.

Bugfix #2265 portals body height

---

src/js/models/maps/GeoPoint.js
test/js/specs/unit/models/maps/GeoPoint.spec.js

This logic will be removed from Viewfinder in future commit.
NCEAS#1796

Move lat, long parsing and validations logic into GeoPoint

---

src/css/map-view.css

Layers list scrolling functionality caused tooltips to not be visible. 
Fix bug while still supporting the layer list scrolling.

Fix overflow issue on toolbar link tooltips

---

src/css/map-view.css
src/js/templates/maps/layers-panel.html
src/js/templates/maps/viewfinder.html
src/js/views/maps/HelpPanelView.js

The new design has a hover effect that highlights the category/layer by changing the background color that covers the full width of the panel (toolbar content). This requires no padding or margin set at the toolbar level.
I also threw in a header fix since we're touching the viewfinder and the help panel. Now the headers should be consistent across the board.
Layers: 
Help:

Layer List Polish 1: Remove padding/margin from toolbar content

---

src/css/map-view.css
src/js/models/maps/assets/MapAsset.js
src/js/templates/maps/layer-item.html
src/js/views/maps/LayerCategoryItemView.js
src/js/views/maps/LayerItemView.js
src/js/views/maps/LayerListView.js
src/js/views/maps/LayersPanelView.js
src/js/views/maps/LegendView.js
test/js/specs/unit/views/maps/LayerCategoryItemView.spec.js
test/js/specs/unit/views/maps/LayerItemView.spec.js
test/js/specs/unit/views/maps/LayerItemViewHarness.js
test/js/specs/unit/views/maps/LayersPanelView.spec.js

Changes:
- Move visibility icon to the left, replacing the current layer's icon.
- Visibility icon decision tree:
- If layer is under a category, use eye icon
- If layer is in a flat list, use layer's icon
- If layer's icon is missing, use "layers" icon as default
- Remove opacity treatment as the layer invisible indicator. Instead, update visibility icon color and hover effect.
- Previously, only visible layers show legend details when you hover over it. Now that there's no opacity treatment to invisible layers, it's less obvious why certain legends don't show details. Remove the `if (visible)` condition from LegendView.
[Light theme flat layers.webm](https://github.com/NCEAS/metacatui/assets/8570665/85e13a11-60e0-488d-ae9c-7e184e70dde7)
[Light theme layer …

Layer List Polish 5: Update layer item styling

---

src/css/map-view.css
src/js/templates/maps/layer-item.html
src/js/views/maps/LayerItemView.js

Changes:
1. Change the visibility click target from the icon to the entire row
2. Change the layer settings click target to a button on the right that contains a gear icon and the legend
3. Implement various stylings for the layer settings button in different states. [Mock](https://www.figma.com/file/9R80DBDAMQtOsu8y1HkAVT/permafrost-discovery-gateway?type=design&node-id=26%3A7115&mode=design&t=nYp86WLQp769PgSt-1)
4. Because the new settings button takes up quite some space, allow layer label to overflow and hide the excess.
Demos:
[Light](https://github.com/NCEAS/metacatui/assets/8570665/c4f096eb-e54f-4df6-95df-ed6e2990651a)
[Dark](https://github.com/NCEAS/metacatui/assets/8570665/b8208cf4-fa0a-42e8-86a8-995d1a02f377)

Layer List Polish 6: Update layer toggles mechanism

---

src/css/map-view.css

Fixes display of viewfinder in the "light" portal theme
Related to issues #1796, #2277

Add margins & theme colors to viewfinder

---

src/js/models/connectors/Filters-Search.js

triggerSearch in Filters-Search connector was resetting the page to 1 because it was passing on arguments from the listener that called it. The argument was triggering the 'resetPage' option in the triggerSearch method.

Allow navigating directly to a page in the Cesium-based data catalog

---

src/js/routers/router.js
src/js/themes/arctic/routers/router.js

Don't allow router to navigate to page numbers <0 in the catalog search
Fixes #2155

Ensure page numbers are always >0 in catalog search

---

src/js/views/maps/LayerItemView.js
src/js/views/maps/LegendView.js

1. Categorical legend still occupies an small empty space even when the color palette doesn't have colors. The fix returns early instead of inserting an empty svg.
Before: <img width="65" alt="image" src="https://github.com/NCEAS/metacatui/assets/8570665/f5aefdb8-4c42-4200-a6e5-3101a9dd8aa7">
After: <img width="50" alt="image" src="https://github.com/NCEAS/metacatui/assets/8570665/bacef4c1-948e-48b0-8aa1-41bc93c609a2">
2. The toggleVisibility function is expected to return early when the event target is the layer settings button, but I noticed that clicking on the edge of the button still toggles on layer visibility. This was because the current check for early return only checks for the button's children components, not itself.
Before: Click here turns on layer settings AND layer …

Layer List Polish: Fix empty legend and layer settings button

---

src/css/map-view.css

This adds a subtle shadow on top of the map to soften the transition from the top navigation bar to the map.
Before
After

Map Components Polish 2: Add top shadow

---

src/css/map-view.css
src/js/views/maps/MapView.js
src/js/views/portals/PortalVisualizationsView.js
test/config/tests.json
test/js/specs/unit/views/maps/MapView.spec.js

As a followup to https://github.com/NCEAS/metacatui/pull/2318, we now keep every layer in one line and use ellipsis if the layer name is too long. Unfortunately that is the case for a lot of our layers on the demo site. The fix is to widen the toolbar panel and layer details view so we can accommodate longer layer names.
Then we face a challenge in the main repository maps that use a 3-part view, where the map view doesn't have enough space for the wide panel. Given that it's a setup only existing in main repositories (for now), we'll apply the wide panel only in portal maps.
Before:
After:
3-part map view in ADC:

Layer List Polish 8: Widen toolbar panel and layer details view

---

src/js/models/maps/assets/CesiumImagery.js
src/js/models/maps/assets/MapAsset.js
test/js/specs/unit/models/maps/assets/CesiumImagery.spec.js

This is so that we can set OpenStreetMaps and the upcoming OpenTopoMap to greyscale.
Demo:

Base Map Polish: Support saturation for CesiumImagery

---

src/js/models/maps/Map.js
src/js/views/maps/CesiumWidgetView.js
test/js/specs/unit/views/maps/CesiumWidgetView.spec.js

Base Map Polish: Support xml config'ed base color for globe

---

src/js/models/maps/assets/CesiumVectorData.js

Because Cesium Billboard only accepts Image or Canvas, we have to do the javascript svg -> image conversion. No good way to use `<i />` or style in map-view.css.
Fixes: #2361

Update Pin Style

---

src/css/map-view.css
src/css/portal-layouts/panels.css
src/css/portal-themes/dark.css
src/css/portal-themes/light.css

We're starting to apply the new color variables outside of the map context. Marking these old variables as deprecate will help us differentiate the new and old as we make incremental progress.
Fixes: #2346

Light theme 8: Deprecate old color variables in themes

---

src/css/map-view.css
src/css/portal-layouts/panels.css
src/css/portal-themes/dark.css
src/css/portal-themes/light.css

I noticed a number of repetitive selector definitions in panels.css. This change consolidated the rules.
Fixes: #2346

Light theme 9: panels.css cleanup

---

src/css/map-view.css
src/js/views/maps/FeatureInfoView.js

Two very small css changes so I'll just put them in one branch.
1. #2344 : Use portal font for feature info iframe when available (Barlow for PDG)
2. #2277 : .layers-panel__layers can host either .layer-list or .layer-category-list. I needed a border for it and wasn't thinking so I added to the children instead. .layer-list is a sharable component so it caused an unwanted border in a different scenario.

Styling Polish: Fixups

---

src/js/collections/maps/viewfinder/ZoomPresets.js
src/js/models/maps/Map.js
src/js/models/maps/viewfinder/ViewfinderModel.js
src/js/models/maps/viewfinder/ZoomPresetModel.js
src/js/templates/maps/viewfinder/viewfinder-zoom-preset.html
src/js/templates/maps/viewfinder/viewfinder.html
src/js/views/maps/viewfinder/SearchView.js
src/js/views/maps/viewfinder/ViewfinderView.js
src/js/views/maps/viewfinder/ZoomPresetView.js
test/config/tests.json
test/js/specs/unit/models/maps/Map.spec.js
test/js/specs/unit/models/maps/viewfinder/ViewfinderModel.spec.js
test/js/specs/unit/views/maps/viewfinder/ViewfinderView.spec.js
test/js/specs/unit/views/maps/viewfinder/ViewfinderViewHarness.js
test/js/specs/unit/views/maps/viewfinder/ZoomPresetView.spec.js
test/js/specs/unit/views/maps/viewfinder/ZoomPresetsListView.spec.js

A subsequent PR will include the appropriate style changes including polish to expansion panels and zoom preset elements. 
This change includes the changes necessary to display a function zoom presets UI, and is hidden behind a Map configuration.

Add zoom presets UI to viewfinder behind showZoomPresets flag

---

src/js/models/maps/Map.js
src/js/models/maps/assets/MapAsset.js
src/js/models/maps/viewfinder/ExpansionPanelsModel.js
src/js/views/maps/ToolbarView.js
src/js/views/maps/viewfinder/ExpansionPanelView.js
src/js/views/maps/viewfinder/ViewfinderView.js
test/js/specs/unit/views/maps/viewfinder/ExpansionPanelView.spec.js

Additionally, viewfinder's zoom presets should start visible. This PR adds support for starting an expansion panel in an expanded (open) state.
NCEAS/metacatui#2397

Update toolbar options to reflect updated ordering and home behavior

---

src/js/common/IconUtilities.js
src/js/models/maps/assets/CesiumVectorData.js
test/js/specs/unit/common/IconUtilities.spec.js

Changes:
- Prevent clipping at the edges of the pin image
- Pin image resolution is higher
- All the non-dynamic changes to the Font Awesome SVG happen only once, outside of the `styleBillboard` method
- Outline width is constant, scales better with changing markerSize
- Add attributes to SVG element not the PATH element
- Remove `fill-rule` (not needed)
Before:
After:

Update pin styles - ideas for further improvements

---

src/css/map-view.css
src/css/portal-layouts/panels.css
src/css/portal-themes/light.css
src/js/views/maps/FeatureInfoView.js

1. Replace current blue- and grey- color variables with primary- and neutral-
2. Remove all semantic color variables I created in the light theme update. Replace them with the primary- and neutral- variables that they reference.
This PR is a part of the plan for new color system. design doc in progress: https://docs.google.com/document/d/1Eb0uixayVeEgO0AcIEjDO6J5555A_CA1BK0nZp1s-uk/edit?usp=sharing We're doing this refactoring first because it will make the legend work a lot simpler.

Portal Theme: Remove semantic color variables

---

src/js/common/SearchParams.js

I missed including this in the last PR somehow. No real functional changes here, but better naming and removing some unnecessary checks.

Use term layer ID instead of layer

---

eslint.config.mjs

ESlint: Allow some unused variables and don't enforce import resolution

---

src/config/config.js
src/js/models/maps/assets/MapAsset.js
src/js/views/maps/LayerDetailsView.js

Added configs for layers in the Map Config

---

helm/templates/deployment.yaml
helm/values.yaml

Change initContainer code to manipulate path for config.js

---

helm/config/nginx-custom.conf
helm/templates/config-js-configmap.yaml
helm/templates/configmap.yaml
helm/templates/deployment.yaml

See #2492 
NOTE - this branch was created from the `feature-2487-k8s-configjs-path` branch, so it will simplify the current PR, if PR #2489 is merged to `develop` first

Feature 2492 k8s nginx cfg

---

src/js/themes/dataone/config.js

Hi @robyngit - one of the tasks for #2375  was to make the QGreenland portal DataONE accessible. 
I've added the config for the same. Adding @mbjones as a reviewer to get his approval for the same. 
This is in draft state because I'm still waiting for the most recent changes from develop to sync this branch. I'll change the status once that is done.

Feature 2375 QGreenland portal

---

src/js/collections/DataPackage.js
src/js/common/Utilities.js
src/js/models/DataONEObject.js
src/js/models/PackageModel.js
src/js/models/SolrResult.js
src/js/views/DataCatalogView.js
src/js/views/DataPackageView.js
src/js/views/DownloadButtonView.js
src/js/views/MetadataIndexView.js
src/js/views/MetadataView.js
src/js/views/PackageTableView.js
src/js/views/StatsView.js
test/js/specs/unit/common/Utilities.spec.js
test/js/specs/unit/models/SolrResult.spec.js

Move bytestoSize to Utilities Ref #2484
[WIP] FH ES Lint issues #2483

File Hierarchy clean up

---

src/js/templates/mdqRun.html
src/js/views/MdqRunView.js

This PR allows markdown to be rendered for any check item on the Metadata Quality view pages. For example, here is a check that has markdown as the output and is rendered as an HTML table:
For the view to render markdown, the "type" property of the "check" in the response must be set to "markdown".
To test these changes, you can override the response in the `parse` method of the `QualityReport` collection (i.e. [here](https://github.com/NCEAS/metacatui/blob/4937596dde0d697d3d921877be441d18a01feac1/src/js/collections/QualityReport.js#L46)). Below is a mock response where the fourth check includes markdown as the output. This resposne is the same as the one Jeanette provided in https://github.com/NCEAS/metacatui/issues/2394#issuecomment-2318655725, except that the `type` has been changed to …

Render metadig text output as markdown

---

src/js/views/filters/FilterEditorView.js

Allow dropdown filter UI for `sem_annotation` field in portal editor

---

src/js/views/MetadataView.js
src/js/views/TableEditorView.js

Before adding another feature to MetadataView and the TableEditorView, a little bit of tidying up:
Part of issue #1758

MetadataView & TableEditorView cleanup (Step 1 of issue #1758)

---

src/js/models/CitationModel.js

Live for testing on https://metacatui.test.dataone.org/
Fixes #2548, Related to #2106

Don't parse author strings in CitationModel

---

src/js/models/metadata/eml211/EMLParty.js
src/js/templates/metadata/EMLParty.html
test/js/specs/unit/models/metadata/eml211/EMLParty.spec.js

- Include unit tests for email validation in spec file
- Also add extra pattern matching in the EML Party template
Fixes #2554

Add email validation to EML Party model

---

src/js/templates/dataItemHierarchy.html
src/js/templates/dataPackageHeader.html
src/js/views/DataItemView.js

- Updated `dataItemHierarchy.html` and `dataPackageHeader.html` to conditionally display metrics based on `AppConfig.displayDatasetMetrics`.
- Fixed a bug in `DataItemView.js` by adding a null check for `this.metricsModel` to prevent `TypeError`.
Closes #2571

fix: update HTML templates and JS to comply with configuration settings

---

.gitignore

Adds CIB theme directory to `.gitignore`.
Closes #2581

adding CIB to .gitignore (#2581)

---

src/js/collections/DataPackage.js
src/js/models/AppModel.js
src/js/views/DataItemView.js
src/js/views/metadata/EML211EditorView.js
test/config/tests.json
test/js/specs/unit/collections/DataPackage.spec.js
test/js/specs/unit/views/DataItemView.spec.js
test/server.js

This pull request addresses two issue tickets related to handling large numbers of files when editing a dataset. One issue involves users uploading tens to hundreds of files at once, which inundates Metacat and leads to unrecoverable upload failures, rendering the dataset unsavable. The other issue pertains to loading the metadata editor when a dataset contains a large number of files. The former fix batches the upload and provides a configuration for `batchSizeUpload`. The latter batches the loading of the system metadata and prevents the user from saving until all data file metadata is loaded, with the batch size configurable via `batchSizeFetch`. Additionally, this pull request implements batch file upload functionality using promises and fixes issues related to loading a large number …

bug: Fixes handing large number data files in Metadata Editor

---

src/js/views/metadata/EML211EditorView.js

Before: waiting for 100 file metadata to load...
After: waiting for metadata from 100 files to load....
Issue #2586

Fix wording on editor button when metadata loading

---

docs/Gemfile.lock
docs/_includes/nav.html
docs/guides/editor/funding-autocomplete.md
docs/guides/helm-deployment.md
docs/guides/index.md
docs/install/helm-k8s.md

see #2480 
* Adds a new guide for installing metacatui using helm
* adds links to nav and index
* fixes inconsistencies in `guides/editor/funding-autocomplete.md`
* fixes incorrect existing entry in index, that causes funding-autocomplete to render as text in browser

Feature 2480 helm guide

---

.gitignore

For development purposes, we add symlinks to the themes directory, but we don’t want them in the remote Git repository, so we typically add them to .gitignore.

Add GOA and ESA themes to gitignore

---

src/js/models/metadata/eml211/EML211.js

The `updateCanonicalDataset` function in the EML211 model expected the `canonicalDataset` property in the model to be an array, but sometimes it gets set as a string. When it was a string, then it was updating the annotation models with the first letter in the string (as opposed to the first item in the array). One letter is not a valid URI, which was why we were sometimes seeing an error. Corrected the function so that it handles both cases, when the `canonicalDataset` property is a string OR when it is an array.
Closes #2616

Fix saving dataset after bad canonical id is set

---

src/js/models/metadata/eml211/EML211.js
src/js/views/metadata/EML211EditorView.js
test/config/tests.json
test/js/specs/unit/views/metadata/EML211EditorView.spec.js

- Addressed issue in `EML211EditorView.showValidation` to correctly display nested validation errors.
- Enhanced `EML211.validate` to handle annotation validation more robustly, preventing null errors.
- Added unit tests to cover the changes in `EML211EditorView.showValidation`.
Fixes #2606

fix(validation): Improve annotations and showValidation error handling

---

src/js/collections/DataPackage.js
src/js/models/AppModel.js
src/js/views/DataItemView.js
src/js/views/metadata/EML211EditorView.js
test/js/specs/unit/collections/DataPackage.spec.js

Builds on top of @vchendrix changes in PR https://github.com/NCEAS/metacatui/pull/2608

Fix & modularize DataPackage fetch methods

---

src/js/views/EditorView.js
src/js/views/metadata/EML211EditorView.js

- Enable tooltips for the "Add Files" button similar to the "Save" button.
- Introduce a `tooltipMessage` parameter to `disableControls` method to display customized messages for disabled buttons.
- Update the `disableControls` call in `EML211EditorView` to include a specific tooltip message.
Closes #2623

feat(editor): enhance button tooltips with dynamic messages

---

docs/docs/SolrResults.html
docs/docs/src_js_collections_SolrResults.js.html
src/js/collections/SolrResults.js
src/js/views/DataCatalogView.js

Fixes issue #1998
Simplifies usePOST logic in SolrResults.js to use POST for queries unless disableQueryPOSTs is true.  Docs are also updated to reflect the change.

fix: use POST for Solr queries to resolve issues with long GET requests

---

src/css/map-view.css
src/js/templates/maps/download-panel.html
src/js/views/maps/DownloadPanelView.js
src/js/views/maps/ToolbarView.js

This PR fixes the layout issue where sometimes the download panel had a large gap between the buttons and other content. To fix it, I had to simplify the layout & css somewhat. Here are the details of the changes I made:
- The `download-panel` view was wrapped in a `draw__tool-panel` div, which added complexity because we were toggling the visibility of both divs to show/hide the download panel. Removing the outer `draw__tool-panel` div made it easier to debug the CSS issues. I could also then remove the CSS rules for the `draw__tool-panel` div and then only needed to adjust the positioning of the `download-panel` div. 
i.e. before:
```html
<div class="toolbar__content toolbar__content--active">
<div class="draw__tool-panel" style="visibility: visible">
<div class="download-panel" …
```

Fix layout issue with download panel in the cesium map

---

src/js/views/maps/DownloadPanelView.js

Currently layers that aren't hosted on the ADC (e.g., carbon layer) do not have a metadata pid associated with them in a map config. The partial download fails for these datasets. This PR is to check if the metadataPid exists before trying to include it in the download.

Metadata pid fix partial download

---

helm/README.md
helm/templates/deployment.yaml
helm/values.yaml

see #2627 - allows user to enable auto-updates for custom themes. If a git repo alredy exists a the path specified in values.yaml, it is updated to the provided tag, or the head of the provided branch. If no repo is found, it is automatically checked out (sparsely, so it contains only the required theme).
PR Also bumps nginx image version from 1.27.0 to 1.29.0

Helm chart theme auto upgrade

---

src/js/models/PackageModel.js
src/js/views/DataItemView.js
src/js/views/DataPackageView.js
src/js/views/DownloadButtonView.js
src/js/views/metadata/EML211EditorView.js

Fixed linting in the following files:
`PackageModel` has a few linting errors left but the plan is to deprecate it so it's better just to leave them.
Changes also include:
- Removing unused imports, variables, and methods
- Simplifying conditional checks and default parameter handling
- Adding missing JSDoc comments
- Removing redundant checks in if statements
Closes #2483

Fix eslint issues in components used for the file hierarchy table

---

src/components/showdown/extensions/showdown-xss-filter/showdown-xss-filter.js
src/js/templates/markdown.html
src/js/templates/portals/editor/MarkdownExample.md
src/js/views/ImageUploaderView.js
src/js/views/MarkdownEditorView.js
src/js/views/MarkdownView.js
src/js/views/portals/editor/PortEditorMdSectionView.js

Collapsible sections are added with `<details>` and `<summary>` tags, allowing users to hide or show content as needed. To allow this, the only change needed was to the `showdown-xss-filter` configuration, which now includes `summary` as an allowed tag (`details` is already allowed).
In addition to the collapsible sections, there is now a button in the markdown editor toolbar to insert these sections easily. There is also an example in the Markdown editor example file to demonstrate how to use this feature.
Additional changes include:
- Fixing all linting errors.
- Moved the very short markdown template into the markdown view directly instead of using a separate template file and increasing the number of HTTP requests.

Add support for collapsible sections in Markdown

---

src/js/views/queryBuilder/QueryBuilderView.js

The view was listening to the select view rather than the select model. Any/All queries not work as expected in the query builder.
Fixes #2587

Fix listener on the ANY/ALL select in QueryBuilder

---

src/js/collections/metadata/eml/EMLAttributes.js
src/js/common/EMLUtilities.js
src/js/models/metadata/eml211/EMLAttributeList.js

This PR fixes a bug with XML serialization of EML <attribute> elements. Most of the codebase still uses HTML-oriented parsing methods like jQuery’s parseHTML, while I've been writing newer code using modern XML APIs. The mix creates a namespace mismatch: elements parsed with parseHTML end up in the HTML namespace, and when these are inserted into an XML DOM and serialized, extra namespace declarations are added. The result is invalid EML output.
To resolve this, a new utility method was introduced to serialize DOM elements to strings while stripping out unwanted namespace attributes. This utility replaces direct calls to XMLSerializer in the two places where <attribute> elements are serialized: the EMLAttributes collection and the EMLAttributeList model.
Closes #2728

Fix bug with namespaces in attribute serialization
