src/js/templates/resultsItem.html, src/js/themes/arctic/templates/resultsItem.html, src/js/themes/dataone/templates/resultsItem.html
=> Fix bug in plural form for 'region(s)' in resultItem templates

src/css/metacatui-common.css, src/js/themes/arctic/css/metacatui.css, src/js/themes/dataone/css/metacatui.css, src/js/themes/default/css/metacatui.css, src/js/themes/goa/css/metacatui.css, src/js/themes/knb/css/metacatui.css, src/js/themes/nceas/css/metacatui.css, src/js/views/MetricModalView.js, src/js/views/MetricsChartView.js
Fixed some minor stylistic issues related to the metrics chart:
1. Updated CSS formatting to resolve problems listed in issue #759 
2. Added custom theme colours for the metric chart line and fill properties, related to [issue #601](https://github.com/NCEAS/metacatui/issues/601#issuecomment-419215303)
=> CSS formatting for metrics modal windows & theme colours for metrics chart

src/js/collections/QualityReport.js
Fix for https://github.com/NCEAS/metacatui/issues/967
=> Only display quality check types once in summary (#967)

src/js/themes/arctic/templates/navbar.html
@laurenwalker just adding a menu item for the Science Advisory Board section that @CSemnacher created in WordPress
=> added SAB navbar item

src/js/models/AppModel.js, src/js/themes/arctic/models/AppModel.js, src/js/themes/dataone/models/AppModel.js, src/js/themes/knb/models/AppModel.js, src/js/themes/nceas/models/AppModel.js, src/js/views/MetadataView.js
Apologies for the horrible branch name.
This change adds a query param that lets Whole Tale know which CN should be used when registering data.
=> Add an api query parameter for the anlyze in whole tale feature

src/js/models/SolrResult.js
Closes #1612
**[ESS-DIVE Tech Debt]** Add project field to SolrResult
Changes SolrResult.getCitationInfo and SolrResult.getInfo to add  project to the list of fields retured.
=> Add project field to SolrResult fields returned

src/js/models/AppModel.js, src/js/themes/arctic/config.js, src/js/themes/dataone/config.js, src/js/themes/knb/config.js
A small one line change to bump the bagit version to 1.0
=> Update the urls.packageServiceUrl to bagit 1.0

src/js/views/metadata/EML211View.js
=> Fix taxa persisting between editor sessions bug

README.md, docs/_config.yml, docs/docs/AccessPolicy.html, docs/docs/AccessRule.html, docs/docs/src_js_collections_AccessPolicy.js.html, docs/docs/src_js_models_AccessRule.js.html, docs/index.md, package.json, src/index.html, src/js/collections/AccessPolicy.js, src/js/models/AccessRule.js
This PR addresses issues with creating and editing datasets in Chrome v120. 
@robyngit  - Please let me know if you see any issues with this, thank you!
=> Bug fix 2235

src/js/themes/default/css/metacatui.css
=> fixing nav dropdown positioning (#1978)

src/js/templates/metadata/metadataOverview.html
=> Update GCMD keyword link in editor

package-lock.json, src/js/app.js, src/js/models/geocoder/GeocodedLocation.js, src/js/models/geocoder/GeocoderSearch.js, src/js/models/geocoder/GoogleMapsAutocompleter.js, src/js/models/geocoder/GoogleMapsGeocoder.js, src/js/models/geocoder/Prediction.js, src/js/models/maps/GeoPoint.js, test/config/tests.json, test/index.html, test/js/specs/shared/mock-gmaps-module.js, test/js/specs/unit/models/geocoder/GeocodedLocation.spec.js, test/js/specs/unit/models/geocoder/GeocoderSearch.spec.js, test/js/specs/unit/models/geocoder/GoogleMapsAutocompleter.spec.js, test/js/specs/unit/models/geocoder/GoogleMapsGeocoder.spec.js, test/js/specs/unit/models/geocoder/Prediction.spec.js
Include additional Google Maps API libraries on page.
Create model services to interact with Google Maps APIs.
NCEAS#1796
=> Use Google Maps API Autocomplete and Geocoder

src/css/map-view.css, src/js/templates/maps/layers-panel.html, src/js/templates/maps/toolbar.html, src/js/templates/maps/viewfinder.html, src/js/views/maps/HelpPanelView.js, src/js/views/maps/ToolbarView.js
...to reflect the new design in the mock: https://www.figma.com/file/9R80DBDAMQtOsu8y1HkAVT/permafrost-discovery-gateway?type=design&node-id=0-852&mode=design&t=u3zHbGgF3OBGco81-4
Demo:
[Remove close button.webm](https://github.com/NCEAS/metacatui/assets/8570665/6de929eb-5a78-4947-a9b3-e184a15604cb)
=> Layer List Polish 2: Remove panel close button

CONTRIBUTING.md
And note how to get in touch with team for questions about contributing.
=> Add PR code review guidelines to the CONTRIBUTING doc

src/css/map-view.css, src/js/models/maps/Map.js, src/js/templates/maps/viewfinder/viewfinder.html, src/js/views/maps/SearchInputView.js, src/js/views/maps/viewfinder/ViewfinderView.js, test/js/specs/unit/views/maps/SearchInputView.spec.js, test/js/specs/unit/views/maps/SearchInputViewHarness.js, test/js/specs/unit/views/maps/viewfinder/ViewfinderView.spec.js, test/js/specs/unit/views/maps/viewfinder/ViewfinderViewHarness.js
Support additional callbacks within SearchInputView for keydown and keyup events
=> Use shared SearchInputView in ViewfinderView

src/css/metacatui-common.css, src/js/views/search/SearchResultsPagerView.js
=> Fix the URL method in new data catalog pager

src/css/catalog-search-view.css, src/css/map-view.css, src/js/models/maps/Map.js, src/js/models/maps/viewfinder/ViewfinderModel.js, src/js/templates/maps/search-input.html, src/js/views/maps/SearchInputView.js, test/js/specs/unit/models/maps/viewfinder/ViewfinderModel.spec.js, test/js/specs/unit/views/maps/SearchInputView.spec.js, test/js/specs/unit/views/maps/SearchInputViewHarness.js
16px = 1rem. I also created border radius variables in map-view.css to standardize it more.
=> Light Theme 4: Convert px to rem

src/css/catalog-search-view.css, src/css/map-view.css, src/css/portal-themes/light.css, src/js/models/maps/Map.js, src/js/models/maps/viewfinder/ViewfinderModel.js, src/js/templates/maps/layer-details.html, src/js/templates/maps/search-input.html, src/js/views/maps/SearchInputView.js, test/js/specs/unit/models/maps/viewfinder/ViewfinderModel.spec.js, test/js/specs/unit/views/maps/SearchInputView.spec.js, test/js/specs/unit/views/maps/SearchInputViewHarness.js
Small adjustments to everything font related including sizes, spacing, and text treatments.
=> Light Theme 5: Adjust text stylings

src/css/catalog-search-view.css, src/css/map-view.css, src/css/portal-themes/light.css, src/js/models/maps/Map.js, src/js/models/maps/viewfinder/ViewfinderModel.js, src/js/templates/maps/layer-details.html, src/js/templates/maps/search-input.html, src/js/views/maps/SearchInputView.js, test/js/specs/unit/models/maps/viewfinder/ViewfinderModel.spec.js, test/js/specs/unit/views/maps/SearchInputView.spec.js, test/js/specs/unit/views/maps/SearchInputViewHarness.js
Small tweaks around colors(including filter, opacity, shadows) and borders.
=> Light Theme 6: Color and border fixups

src/js/models/maps/viewfinder/ViewfinderModel.js, src/js/views/maps/SearchInputView.js, src/js/views/maps/viewfinder/ViewfinderView.js, test/js/specs/unit/models/maps/viewfinder/ViewfinderModel.spec.js, test/js/specs/unit/views/maps/SearchInputView.spec.js, test/js/specs/unit/views/maps/viewfinder/ViewfinderView.spec.js, test/js/specs/unit/views/maps/viewfinder/ViewfinderViewHarness.js
[Various query combinations that previously caused issue.webm](https://github.com/NCEAS/metacatui/assets/4664309/f727dffd-431c-43c8-9915-591fb75202a1)
=> Fix issue with error not being cleared when user deletes and retypes queries

src/js/themes/arctic/css/metacatui.css
=> Fix path to ADC logo img on portal nav

src/css/portal-layouts/panels.css, src/css/portal-themes/light.css
=> Light theme 10: Navigation bar polish

src/css/map-view.css, src/js/views/maps/legend/ContinuousSwatchView.js, src/js/views/maps/legend/LayerLegendView.js, test/js/specs/unit/views/maps/legend/ContinuousSwatchView.spec.js
1. Take into consideration of "min"/"max" as the value of a continuous palette. The exact values of these fields can change based on the viewport.
2. Lower the max height of legend now that we've added the share link button to toolbar link.
=> Legend: Bug bash fixes

src/js/models/maps/Map.js, src/js/views/maps/LayerDetailsView.js
This PR resolves the issue introduced in the previous commit. It also addressed ReviewDog and lining problems that were present in the old code.
=> Bugfix-2498-added checks for model + fixed syntax in the old code

helm/config/config.js, helm/values.yaml
git cherry-pick 88e1fb1d0aaf58395a464824a6361dc6158225ab, to incorporate the changes from PR #2563
=> helm 1.0.0 release cherry-pick

src/js/models/AppModel.js
=> Add missing HRs to `AppModel.js` to address #2614

README.md, docs/_config.yml, docs/docs/AppConfig.html, docs/docs/AppModel.html, docs/docs/DataItemView.html, docs/docs/DataPackage.html, docs/docs/EML211.html, docs/docs/EML211EditorView.html, docs/docs/src_js_collections_DataPackage.js.html, docs/docs/src_js_models_AppModel.js.html, docs/docs/src_js_models_metadata_eml211_EML211.js.html, docs/docs/src_js_views_DataItemView.js.html, docs/docs/src_js_views_metadata_EML211EditorView.js.html, docs/index.md, helm/Chart.yaml, package.json, src/index.html, src/js/collections/DataPackage.js, src/js/models/AppModel.js, src/js/models/metadata/eml211/EML211.js, src/js/themes/arctic/config.js, src/js/themes/knb/config.js, src/js/views/DataItemView.js, src/js/views/metadata/EML211EditorView.js
- Update version numbers
- Rebuild docs
- Fix minor issue found during testing
=> Release tasks 2.32.1

src/js/models/metadata/eml211/EML211.js
=> Ensure EML is marked as not new after first save

src/css/map-view.css, src/js/templates/maps/layer-item.html, src/js/views/maps/LayerItemView.js, src/js/views/maps/VectorFilterView.js, src/js/views/maps/legend/CategoricalSwatchView.js, src/js/views/maps/legend/LayerLegendView.js, src/js/views/maps/legend/LegendContainerView.js
**See issue https://github.com/NCEAS/metacatui/issues/2714 **
Adjust the look of labels in the legend, based on whether the feature layer is visible on the map or not. This adjustment is a change in label transparency. In addition, also allow the user to select (i.e., show/hide) vector layers based on pre-configured filter values directly from the legend view.
This UI adjustment is a first iteration of testing whether this is an ideal way to show/hide vector feature layers directly from the legend.
This feature is an improvement to the "Filter by Property" feature (see issue https://github.com/NCEAS/metacatui/issues/1770).
**Base code:** Include code updates presented in PR ##2723.
Additionally,
1. Added the layer-item class to each swatch item in the legend. Re-using the class that was …
=> Update legend swatches to show/hide vector feature layers directly from the legend
